mariadb_root_password: vagrant
librenms_db_password: vagrant
community_string: CHANGEME
v1_community_string: CHANGEME
v2_community_string: CHANGEME
v3_credentials:
  username: CHANGEME
  auth_key: CHANGEME
  priv_key: CHANGEME
  priv_protocol: AES
  auth_protocol: SHA
