- name: Forward port 161 to 1611
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    in_interface: eth1
    protocol: udp
    match: udp
    destination_port: 161
    jump: REDIRECT
    to_ports: 1611
  become: yes

- name: Starting snmpv3 simulator
  become_user: vagrant
  shell: |
    snmpsim-command-responder --data-dir=/home/vagrant/data/v3 --agent-udpv4-endpoint=0.0.0.0:1611 --v3-user {{ v3_credentials.username }} --v3-auth-proto={{ v3_credentials.auth_protocol }} --v3-auth-key={{ v3_credentials.auth_key}} --v3-priv-proto={{ v3_credentials.priv_protocol }} --v3-priv-key={{ v3_credentials.priv_key }} --v3-only --daemonize
